version: '3.8'

services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped
