name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Health Check
        run: curl -s https://restaurant-system-jtp3.onrender.com/api/ishealthy
